"""family_graph and sessions tables

Revision ID: 47a1b29de8db
Revises: 
Create Date: 2026-08-20 05:54:03.378324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47a1b29de8db"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_graphs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "family_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("family_graph_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "relation",
            sa.Enum(
                "spouse",
                "child",
                "parent",
                "grandchild",
                "sibling",
                "grandparent",
                name="relation_type",
            ),
            nullable=False,
        ),
        sa.Column("is_alive", sa.Boolean(), nullable=False),
        sa.Column("is_minor", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_graph_id"], ["family_graphs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_family_members_family_graph_id"),
        "family_members",
        ["family_graph_id"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=200), nullable=False),
        sa.Column("family_graph_id", sa.String(length=32), nullable=True),
        sa.Column("last_agent", sa.String(length=50), nullable=True),
        sa.Column("pending_handoff", sa.String(length=50), nullable=True),
        sa.Column("per_agent_context", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_graph_id"], ["family_graphs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.drop_index(
        op.f("ix_family_members_family_graph_id"), table_name="family_members"
    )
    op.drop_table("family_members")
    op.drop_table("family_graphs")
    # ### end Alembic commands ###
    # 수동 추가: 테이블을 드롭해도 Postgres의 ENUM 타입(relation_type)은 남아있어서,
    # 그대로 두면 다음 upgrade()에서 "type already exists"로 실패합니다.
    sa.Enum(name="relation_type").drop(op.get_bind(), checkfirst=True)
